### ISSUE TITLE
republish 2.1.0 as 3.0.0 (and unpublish 2.1.0) 

### ISSUE THREAD

**Issue by calvinmetcalf** [indutny/miller-rabin#4]
the upgrade to bn.js@3.1.1 is a breaking change crypto-browserify/crypto-browserify#133

**Comment by indutny** [comment]
Thanks! Decided to do it in a radical way, and gave away both git and npm rights to you :)

**Comment by calvinmetcalf** [comment]
sweet thanks!

**Comment by calvinmetcalf** [comment]
fixed!
