### ISSUE TITLE
miller-radbin@2.1.0 no longer working?

### ISSUE THREAD

**Issue by jhchill666** [indutny/miller-rabin#5]
As of yesterday, which coincidentally seems to coincide with your release of version 3.0.0, version 2.1.0 is no longer available and causing npm installation errors.

Is there anything that can be done to remedy this, as miller-rabin is a deeply nested dependency and I have no control over changing the version.

**Comment by indutny** [comment]
cc @calvinmetcalf

**Comment by indutny** [comment]
I think we should probably do a release of 2.1.1 with older bn.js version.

**Comment by calvinmetcalf** [comment]
I can do that in about an hour,  @jamiehill the issue was that 2.1.0 had a breaking change in it so I unpunished it and republished as 3.0.0

**Comment by jhchill666** [comment]
Cheers guys. Seems to be installing correctly now

**Comment by calvinmetcalf** [comment]
so we're good? I mean the only dependents are me (with diffie-hellman), you @indutny with self signed and 2 by @wanderer one is at ^3.0.0 and one is at ^2.0.1 so would not be affected

**Comment by wanderer** [comment]
tested and good here :)

**Comment by sghall** [comment]
The missing version is causing an error doing a JSPM install....thoughts?
![screen shot 2015-08-20 at 4 33 36 pm](https://cloud.githubusercontent.com/assets/4615775/9398232/819cb11c-4759-11e5-8a0f-2e2548ba722a.png)

**Comment by calvinmetcalf** [comment]
Can you do a cache clean in jspm to get it to forget about that version or
if not where is that being saved?

**Comment by danbucholtz** [comment]
Can you republish 2.1?  I am seeing npm install issues on popular tools like browserify, etc.  It is a deeply nested dependency.

**Comment by calvinmetcalf** [comment]
@danbucholtz do `npm cache clean` and that should go away

**Comment by danbucholtz** [comment]
@calvinmetcalf, I did that as well as purge the ~/.npm directory.  It seems the issue still exists.

npm WARN peerDependencies The peer dependency bluebird@~2.2.1 included from pogo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> spawn-sync@1.0.13 postinstall /Users/danbucholtz/Dev/b3-file-storage-service/node_modules/@brady/core-gulp/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync
> node postinstall

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.0.2
npm ERR! npm  v2.9.0

npm ERR! version not found: miller-rabin@2.1.0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by calvinmetcalf** [comment]
I can republish Tuesday as I'm not near a computer, considering nothing in
browserify explicitly depends on 2.1.0 (it  depends on ^2.0.0) you should
double check how npm is set up for you.

**Comment by calvinmetcalf** [comment]
ok back @danbucholtz are you still having problems? if so I can publish 2.1.1, which should fix things if the issue is that a dependency is depending on ~2.1.0, I can't actually republish 2.1.0 because npm doesn't allow you to do that.

**Comment by danbucholtz** [comment]
It seems like we're back up and running again.  Our npm installs are no longer failing.  Thanks!

**Comment by galenspindel** [comment]
This issue has resurfaced for 2.1.0. Yesterday all npm installs worked, today they are failing.

**Comment by calvinmetcalf** [comment]
trying to reproduce, what exactly are you trying to install ?

**Comment by calvinmetcalf** [comment]
and what version of npm

**Comment by andrei-m** [comment]
Our team is running into this with 2.1.0 being a dependency of diffie-helman, which is itself a dependency crypto-browserify, which browserify needs. Here's the diffie-hellman dependency:

```
"diffie-hellman": {
  "version": "3.0.2",
  "from": "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-3.0.2.tgz",
  "resolved": "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-3.0.2.tgz",
  "dependencies": {
    "bn.js": {
      "version": "2.2.0",
      "from": "https://registry.npmjs.org/bn.js/-/bn.js-2.2.0.tgz",
      "resolved": "https://registry.npmjs.org/bn.js/-/bn.js-2.2.0.tgz"
    },   
    "miller-rabin": {
      "version": "2.1.0",
      "from": "https://registry.npmjs.org/miller-rabin/-/miller-rabin-2.1.0.tgz",
      "resolved": "https://registry.npmjs.org/miller-rabin/-/miller-rabin-2.1.0.tgz",
      "dependencies": {
        "bn.js": {
          "version": "3.1.1",
          "from": "https://registry.npmjs.org/bn.js/-/bn.js-3.1.1.tgz",
          "resolved": "https://registry.npmjs.org/bn.js/-/bn.js-3.1.1.tgz"
        },   
        "brorand": {
          "version": "1.0.5",
          "from": "https://registry.npmjs.org/brorand/-/brorand-1.0.5.tgz",
          "resolved": "https://registry.npmjs.org/brorand/-/brorand-1.0.5.tgz"
        }    
      }    
    }    
  }    
}   
```

**Comment by plumlee** [comment]
Seeing the same issue here as @andrei-m, same dependency tree. Would you be open to publishing a 2.1.1 as mentioned above?

UPDATE - turns out I had upgraded us to v13 of browserify, and it's not an issue there. Someone was doing a build using an older version where it still had this dependency. No change needed after all.

**Comment by noahgrant** [comment]
@calvinmetcalf on npm v2.11.3, and we're seeing it no longer available on npm:

![screen shot 2016-03-21 at 9 55 46 am](https://cloud.githubusercontent.com/assets/1355779/13926796/24e3e48c-ef4b-11e5-99d6-981a29d53a6b.png)

**Comment by calvinmetcalf** [comment]
version 2.1.0 was removed from npm in august I can only surmise you had some sort of weird local caching issue

**Comment by noahgrant** [comment]
interesting, and you're probably right, but why would you just remove it instead of keeping it around for people running old versions of libraries?

**Comment by calvinmetcalf** [comment]
it was published for several days max and actively broke running code

**Comment by andrei-m** [comment]
For what it's worth, we put this hack into the npm-shrinkwrap.json for our project. This allows NPM to find the specific miller-rabin version, despite it being missing from the NPM index. In case it's helpful for others, in a pinch:

```
--- a/npm-shrinkwrap.json
+++ b/npm-shrinkwrap.json
@@ -694,8 +694,8 @@
                 },
                 "miller-rabin": {
                   "version": "2.1.0",
-                  "from": "https://registry.npmjs.org/miller-rabin/-/miller-rabin-2.1.0.tgz",
-                  "resolved": "https://registry.npmjs.org/miller-rabin/-/miller-rabin-2.1.0.tgz",
+                  "from": "https://github.com/indutny/miller-rabin/archive/v2.1.0.tar.gz",
+                  "resolved": "https://github.com/indutny/miller-rabin/archive/v2.1.0.tar.gz",
                   "dependencies": {
                     "bn.js": {
                       "version": "3.1.1",
```

**Comment by aredridel** [comment]
All y'all on older npms, update. There were caching bugs in some releases!
