### ISSUE TITLE
Hard Coded Lower Bits of Random Numbers

### ISSUE THREAD

**Issue by deckar01** [indutny/miller-rabin#6]
```js
// Set low bits
buf[0] |= 3;
```

https://github.com/indutny/miller-rabin/commit/6cd58b7c1abbcb05abca1b921895ce033d0e7002#diff-e97122c55a922fd3b8e005898a3c25e3R9

Why are the lower 2 bits of the random bases being set to `1`? Is there something special about bases of the form `4x + 3`?

A quick analysis of the composites under 1000 that have both witnesses and non-witnesses indicates that ~25.4% non-witnesses have the form `4x+3`. This indicates that you might be skewing the random number generator towards bases that are poorer indicators of compositeness.

**Comment by indutny** [comment]
To be honest, I no longer remember why I did that change 😭 

If you want to open a PR to fix this along with explanation - I'd be happy to merge it.

**Comment by deckar01** [comment]
I continued running my analysis and as the numbers grow the odds tend towards 25%, which means it probably doesn't harm large numbers, but it doesn't help them either.

Since there is no theoretical basis for only using `4x + 3` bases, I will open a PR to remove this restriction.

**Comment by indutny** [comment]
Thanks!

**Comment by calvinmetcalf** [comment]
ok so filping the last bit is to make sure it's odd that one should be
obvious, as for the other bit, for most diffie-hellmen stuff you want a
'safe prime' where (p-1)/2  is also prime, so setting the penultimate bit
to be 1 makes sure that (p-1)/2  is also odd

**Comment by deckar01** [comment]
@calvinmetcalf `_rand()` isn't being used to pick candidates for prime numbers. It is being used to pick bases that are potential witnesses to the compositeness of the input number. There is no research I am aware of that supports the exclusion of any class of Miller-Rabin bases.

https://github.com/indutny/miller-rabin/blob/d6182d9/lib/mr.js#L46
